version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(submodule)"
      include: "scope"
    labels: ["dependencies", "submodule", "auto-update"]
    open-pull-requests-limit: 3
